name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Install dependencies
        id: install
        run: |
          pnpm install --frozen-lockfile
      - name: Build
        id: build
        run: |
          pnpm run build
